config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :users, only: [:new, :create, :show]

  get 'session/new', to: 'sessions#new', as: 'new_session'
  post 'session', to:'sessions#create', as: 'session'
  delete 'session', to:'sessions#destroy', as: 'session_destroy'

  resources :subs, except: [:destroy]
  resources :posts, except: [:destroy, :index]
=======

  resources :contact_shares, only: :destroy
  resources :users do
    resources :contacts
  end

>>>>>>> df507360b6b87b8b4b69fe0523f2dca32d06e03e
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :sub_id, :author_id, presence: true

  belongs_to :sub

  belongs_to :author,
    foreign_key: :author_id,
    primary_key: :id, 
    class_name: "User"
end

app/controllers/posts_controller.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostsController < ApplicationController
  def create
    post = Post.new(post_params)
    if post && post.save
      redirect_to post_url(post)
    else
      flash[:notice] = "Silly post, try again"
      redirect_to new_post_url
    end
  end

  def show
    @post = Post.find_by_id(params[:id])
    if @post
      render :show
    else
      redirect_to subs_url
    end
  end

  def update
    post = Post.find_by_id(params[:id])
    if post && post.update(post_params)
      redirect_to post_url(post)
    else
      flash[:notice] = "You are a horrible person"
      redirect_to edit_post_url
    end
    
  end
  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id, :author_id)
  end
end

app/helpers/posts_helper.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module PostsHelper
end

app/views/posts/_form.html.erb
<% url = sub ? sub_url : subs_url %>
<% submit_str = sub ? "Update" : "Create" %>
<% method = sub ? "PATCH" : "POST" %>

<form action="<%=url%>" method="POST">
  <input type="hidden" name="_method" value="<%=method%>" />
  <%= auth_token %>

  <label for="title">Title:</label>
  <input type="text" id="title" name="sub[title]" value="<%= sub.title %>"/>
  <br>

  <label for="description">Description:</label>
  <textarea
    value="<%=sub.description%>"
    id="description"
    name="sub[description]" cols="20" rows="8"><%=sub.description%></textarea>
  <input type="submit" value="<%= submit_str %>" />
</form>

app/views/posts/_post.html.erb
<h3>+ <%= post.title %> </h3>
<p>+ <%= post.author.email %>, <%= post.sub.title %>, <%= post.url%> </p>
<p>+ <%= post.content %> </p>